import type { EnemyDefinition, EnemyRole, MissionEnemyWaveEntry } from '../types/game';

export const ENEMY_DEFINITIONS: Record<EnemyRole, EnemyDefinition> = {
  'fast-interceptor': {
    role: 'fast-interceptor',
    label: 'Fast Interceptor',
    silhouette: 'needle-frame',
    health: 45,
    shields: 0,
    speed: 0.55,
    minRange: 55,
    maxRange: 95,
    drift: 0.16,
    fireCooldownMs: 2200,
    projectileSpeed: 2.7,
    projectileDamage: 9,
    scoreValue: 250,
    color: 0xff2a2a,
    emissive: 0xff0000,
    scale: [1, 1, 1],
  },
  'heavy-gunship': {
    role: 'heavy-gunship',
    label: 'Heavy Gunship',
    silhouette: 'wide-armored-frame',
    health: 95,
    shields: 20,
    speed: 0.32,
    minRange: 85,
    maxRange: 150,
    drift: 0.08,
    fireCooldownMs: 3000,
    projectileSpeed: 2.3,
    projectileDamage: 13,
    scoreValue: 425,
    color: 0xff6a00,
    emissive: 0xaa2200,
    scale: [1.45, 1.15, 1.45],
  },
  'missile-platform': {
    role: 'missile-platform',
    label: 'Missile Platform',
    silhouette: 'long-range-rail-frame',
    health: 65,
    shields: 10,
    speed: 0.24,
    minRange: 140,
    maxRange: 260,
    drift: 0.05,
    fireCooldownMs: 3600,
    projectileSpeed: 2.0,
    projectileDamage: 18,
    scoreValue: 500,
    color: 0xff0044,
    emissive: 0xff0033,
    scale: [1.2, 0.9, 1.8],
  },
  'shielded-warden': {
    role: 'shielded-warden',
    label: 'Shielded Warden',
    silhouette: 'shield-core-frame',
    health: 80,
    shields: 60,
    speed: 0.28,
    minRange: 95,
    maxRange: 180,
    drift: 0.06,
    fireCooldownMs: 3300,
    projectileSpeed: 2.2,
    projectileDamage: 12,
    scoreValue: 550,
    color: 0x7c4dff,
    emissive: 0x4b22ff,
    scale: [1.25, 1.4, 1.25],
  },
  'mini-boss': {
    role: 'mini-boss',
    label: 'Command Frigate',
    silhouette: 'boss-command-frame',
    health: 220,
    shields: 120,
    speed: 0.18,
    minRange: 180,
    maxRange: 320,
    drift: 0.03,
    fireCooldownMs: 2200,
    projectileSpeed: 2.4,
    projectileDamage: 16,
    scoreValue: 1500,
    color: 0xffffff,
    emissive: 0xff5500,
    scale: [2.2, 1.4, 2.8],
  },
  // Stage 5c: ace enemy for air-to-air intercept missions
  'ace-interceptor': {
    role: 'ace-interceptor',
    label: 'Ace Fighter',
    silhouette: 'needle-frame',
    health: 160,
    shields: 80,
    speed: 0.72,
    minRange: 40,
    maxRange: 110,
    drift: 0.42,
    fireCooldownMs: 1400,
    projectileSpeed: 3.4,
    projectileDamage: 11,
    scoreValue: 900,
    color: 0xff4466,
    emissive: 0xff0033,
    scale: [0.85, 0.85, 0.85],
  },
};

export const ENEMY_PROGRESSION_PLAN: MissionEnemyWaveEntry[] = [
  { role: 'fast-interceptor', count: 2 },
  { role: 'heavy-gunship', count: 2 },
  { role: 'missile-platform', count: 1 },
  { role: 'shielded-warden', count: 1 },
  { role: 'mini-boss', count: 1 },
];

export function getEnemyDefinition(role: EnemyRole) {
  return ENEMY_DEFINITIONS[role];
}

export function expandEnemyWave(composition: MissionEnemyWaveEntry[]) {
  return composition.flatMap(entry => Array.from({ length: entry.count }, () => getEnemyDefinition(entry.role)));
}
