import type { MissionDefinition } from '../types/game';
import { IRON_VEIL_ENVIRONMENT, SIGNAL_BREAK_ENVIRONMENT } from './environments';

export const MISSIONS: MissionDefinition[] = [
  {
    id: 'signal-break',
    order: 1,
    title: 'SIGNAL BREAK',
    campaignArc: 'Arc 1 // Signal War',
    difficulty: 1,
    targetLabel: 'Radar Towers',
    initialObjective: 'DESTROY RADAR TOWERS',
    targetDestroyedMessage: 'RADAR TOWER DESTROYED',
    nextTargetMessage: 'CHARTING NEW TARGET...',
    allTargetsDestroyedMessage: 'ALL TARGETS NEUTRALIZED // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '3 Towers' },
      { label: 'Extraction', value: 'North Zone' },
      { label: 'Threat', value: 'Interceptors' },
    ],
    targets: [
      { id: 'tower_0', position: [400, 0, -400], health: 100 },
      { id: 'tower_1', position: [-550, 0, 200], health: 100 },
      { id: 'tower_2', position: [100, 0, 700], health: 100 },
    ],
    extraction: {
      label: 'North Zone',
      position: [0, 0, -1200],
      activationObjective: 'RETREAT TO EXTRACTION POINT',
      approachObjective: 'RETREAT TO EXTRACTION POINT',
      completionObjective: 'MISSION COMPLETE',
      radius: 80,
    },
    enemyWave: {
      triggerTargetsDestroyed: 2,
      count: 2,
      message: 'WARNING: ENEMY INTERCEPTORS INBOUND',
      composition: [
        { role: 'fast-interceptor', count: 2 },
      ],
    },
    environment: SIGNAL_BREAK_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO MISSION AREA' },
    ],
    scoring: {
      parTimeMs: 180000,
      baseScore: 1000,
      targetBonus: 700,
      enemyBonus: 250,
      healthBonus: 10,
      timeBonus: 500,
      rankThresholds: { S: 4500, A: 3600, B: 2800, C: 0 },
    },
    reward: {
      id: 'extraction-protocol',
      label: 'Extraction Protocol',
      description: 'Campaign command authorizes follow-on sorties and unlocks the Ion Missile secondary weapon.',
    },
  },
  {
    id: 'iron-veil',
    order: 2,
    title: 'IRON VEIL',
    campaignArc: 'Arc 1 // Signal War',
    difficulty: 2,
    targetLabel: 'Relay Spires',
    initialObjective: 'DESTROY RELAY SPIRES',
    targetDestroyedMessage: 'RELAY SPIRE DESTROYED',
    nextTargetMessage: 'RECALCULATING RELAY GRID...',
    allTargetsDestroyedMessage: 'RELAY GRID DARK // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '4 Spires' },
      { label: 'Extraction', value: 'East Ridge' },
      { label: 'Threat', value: 'Heavy Patrol' },
    ],
    targets: [
      { id: 'spire_0', position: [520, 0, -520], health: 100 },
      { id: 'spire_1', position: [-650, 0, -180], health: 100 },
      { id: 'spire_2', position: [-120, 0, 760], health: 100 },
      { id: 'spire_3', position: [760, 0, 260], health: 100 },
    ],
    extraction: {
      label: 'East Ridge',
      position: [1250, 0, 0],
      activationObjective: 'RETREAT TO EAST RIDGE',
      approachObjective: 'RETREAT TO EAST RIDGE',
      completionObjective: 'MISSION COMPLETE',
      radius: 90,
    },
    enemyWave: {
      triggerTargetsDestroyed: 2,
      count: 3,
      message: 'WARNING: HEAVY PATROL VECTORING IN',
      composition: [
        { role: 'heavy-gunship', count: 2 },
        { role: 'missile-platform', count: 1 },
      ],
    },
    environment: IRON_VEIL_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO EASTERN COMBAT ZONE' },
    ],
    scoring: {
      parTimeMs: 240000,
      baseScore: 1300,
      targetBonus: 750,
      enemyBonus: 275,
      healthBonus: 10,
      timeBonus: 650,
      rankThresholds: { S: 5600, A: 4500, B: 3400, C: 0 },
    },
    reward: {
      id: 'relay-grid-intel',
      label: 'Relay Grid Intel',
      description: 'Recovered routing data opens denser patrol corridors for the next campaign arc.',
    },
    unlockAfterMissionId: 'signal-break',
  },
  {
    id: 'black-sky-hook',
    order: 3,
    title: 'BLACK SKY HOOK',
    campaignArc: 'Arc 1 // Signal War',
    difficulty: 3,
    targetLabel: 'Uplink Masts',
    initialObjective: 'DESTROY UPLINK MASTS',
    targetDestroyedMessage: 'UPLINK MAST DESTROYED',
    nextTargetMessage: 'SEEKING NEXT UPLINK...',
    allTargetsDestroyedMessage: 'SIGNAL NET COLLAPSED // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '5 Masts' },
      { label: 'Extraction', value: 'South Gate' },
      { label: 'Threat', value: 'Interceptor Screen' },
    ],
    targets: [
      { id: 'mast_0', position: [420, 0, -720], health: 110 },
      { id: 'mast_1', position: [-720, 0, -420], health: 110 },
      { id: 'mast_2', position: [-680, 0, 520], health: 110 },
      { id: 'mast_3', position: [240, 0, 820], health: 110 },
      { id: 'mast_4', position: [820, 0, 220], health: 110 },
    ],
    extraction: {
      label: 'South Gate',
      position: [0, 0, 1350],
      activationObjective: 'RETREAT TO SOUTH GATE',
      approachObjective: 'RETREAT TO SOUTH GATE',
      completionObjective: 'MISSION COMPLETE',
      radius: 90,
    },
    enemyWave: {
      triggerTargetsDestroyed: 2,
      count: 4,
      message: 'WARNING: INTERCEPTOR SCREEN ACTIVE',
      composition: [
        { role: 'fast-interceptor', count: 3 },
        { role: 'heavy-gunship', count: 1 },
      ],
    },
    environment: SIGNAL_BREAK_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO SIGNAL WAR ZONE' },
    ],
    scoring: {
      parTimeMs: 270000,
      baseScore: 1500,
      targetBonus: 800,
      enemyBonus: 300,
      healthBonus: 10,
      timeBonus: 700,
      rankThresholds: { S: 7000, A: 5600, B: 4200, C: 0 },
    },
    reward: {
      id: 'arc-two-clearance',
      label: 'Arc Two Clearance',
      description: 'Command opens the Blackout Line and authorizes denser threat corridors.',
    },
    unlockAfterMissionId: 'iron-veil',
  },
  {
    id: 'blackout-line',
    order: 4,
    title: 'BLACKOUT LINE',
    campaignArc: 'Arc 2 // Blackout Line',
    difficulty: 4,
    targetLabel: 'Jammer Pylons',
    initialObjective: 'DESTROY JAMMER PYLONS',
    targetDestroyedMessage: 'JAMMER PYLON DESTROYED',
    nextTargetMessage: 'JAMMER CHAIN REFORMING...',
    allTargetsDestroyedMessage: 'BLACKOUT LINE OPEN // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '5 Pylons' },
      { label: 'Extraction', value: 'West Corridor' },
      { label: 'Threat', value: 'Missile Platforms' },
    ],
    targets: [
      { id: 'pylon_0', position: [620, 0, -780], health: 120 },
      { id: 'pylon_1', position: [-840, 0, -360], health: 120 },
      { id: 'pylon_2', position: [-460, 0, 720], health: 120 },
      { id: 'pylon_3', position: [420, 0, 860], health: 120 },
      { id: 'pylon_4', position: [920, 0, 80], health: 120 },
    ],
    extraction: {
      label: 'West Corridor',
      position: [-1450, 0, 120],
      activationObjective: 'RETREAT TO WEST CORRIDOR',
      approachObjective: 'RETREAT TO WEST CORRIDOR',
      completionObjective: 'MISSION COMPLETE',
      radius: 95,
    },
    enemyWave: {
      triggerTargetsDestroyed: 2,
      count: 4,
      message: 'WARNING: MISSILE PLATFORMS ACQUIRING LOCK',
      composition: [
        { role: 'missile-platform', count: 2 },
        { role: 'fast-interceptor', count: 2 },
      ],
    },
    environment: IRON_VEIL_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO BLACKOUT LINE' },
    ],
    scoring: {
      parTimeMs: 300000,
      baseScore: 1700,
      targetBonus: 850,
      enemyBonus: 325,
      healthBonus: 10,
      timeBonus: 800,
      rankThresholds: { S: 7800, A: 6200, B: 4700, C: 0 },
    },
    reward: {
      id: 'missile-threat-intel',
      label: 'Missile Threat Intel',
      description: 'Enemy launch signatures are cataloged for deeper line strikes.',
    },
    unlockAfterMissionId: 'black-sky-hook',
  },
  {
    id: 'warden-break',
    order: 5,
    title: 'WARDEN BREAK',
    campaignArc: 'Arc 2 // Blackout Line',
    difficulty: 5,
    targetLabel: 'Shield Nodes',
    initialObjective: 'DESTROY SHIELD NODES',
    targetDestroyedMessage: 'SHIELD NODE DESTROYED',
    nextTargetMessage: 'WARDEN SHIELD REROUTING...',
    allTargetsDestroyedMessage: 'WARDEN NET DOWN // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '6 Nodes' },
      { label: 'Extraction', value: 'Northwest Shelf' },
      { label: 'Threat', value: 'Shielded Wardens' },
    ],
    targets: [
      { id: 'node_0', position: [540, 0, -900], health: 120 },
      { id: 'node_1', position: [-520, 0, -820], health: 120 },
      { id: 'node_2', position: [-900, 0, -20], health: 120 },
      { id: 'node_3', position: [-520, 0, 820], health: 120 },
      { id: 'node_4', position: [480, 0, 880], health: 120 },
      { id: 'node_5', position: [900, 0, 40], health: 120 },
    ],
    extraction: {
      label: 'Northwest Shelf',
      position: [-1100, 0, -1180],
      activationObjective: 'RETREAT TO NORTHWEST SHELF',
      approachObjective: 'RETREAT TO NORTHWEST SHELF',
      completionObjective: 'MISSION COMPLETE',
      radius: 100,
    },
    enemyWave: {
      triggerTargetsDestroyed: 3,
      count: 5,
      message: 'WARNING: SHIELDED WARDENS DEPLOYED',
      composition: [
        { role: 'shielded-warden', count: 2 },
        { role: 'heavy-gunship', count: 2 },
        { role: 'fast-interceptor', count: 1 },
      ],
    },
    environment: IRON_VEIL_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO WARDEN ZONE' },
    ],
    scoring: {
      parTimeMs: 330000,
      baseScore: 1900,
      targetBonus: 875,
      enemyBonus: 350,
      healthBonus: 10,
      timeBonus: 900,
      rankThresholds: { S: 9000, A: 7200, B: 5400, C: 0 },
    },
    reward: {
      id: 'warden-code-fragment',
      label: 'Warden Code Fragment',
      description: 'Recovered shield telemetry exposes command-frigate routing.',
    },
    unlockAfterMissionId: 'blackout-line',
  },
  {
    id: 'ember-crown',
    order: 6,
    title: 'EMBER CROWN',
    campaignArc: 'Arc 2 // Blackout Line',
    difficulty: 6,
    targetLabel: 'Crown Relays',
    initialObjective: 'DESTROY CROWN RELAYS',
    targetDestroyedMessage: 'CROWN RELAY DESTROYED',
    nextTargetMessage: 'EMBER CROWN REBALANCING...',
    allTargetsDestroyedMessage: 'EMBER CROWN BROKEN // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '6 Relays' },
      { label: 'Extraction', value: 'Ash Cut' },
      { label: 'Threat', value: 'Mixed Patrol' },
    ],
    targets: [
      { id: 'crown_0', position: [720, 0, -860], health: 130 },
      { id: 'crown_1', position: [-760, 0, -780], health: 130 },
      { id: 'crown_2', position: [-980, 0, 160], health: 130 },
      { id: 'crown_3', position: [-240, 0, 960], health: 130 },
      { id: 'crown_4', position: [660, 0, 780], health: 130 },
      { id: 'crown_5', position: [1020, 0, -120], health: 130 },
    ],
    extraction: {
      label: 'Ash Cut',
      position: [1420, 0, 920],
      activationObjective: 'RETREAT TO ASH CUT',
      approachObjective: 'RETREAT TO ASH CUT',
      completionObjective: 'MISSION COMPLETE',
      radius: 105,
    },
    enemyWave: {
      triggerTargetsDestroyed: 3,
      count: 6,
      message: 'WARNING: MIXED PATROL COMMITTING',
      composition: [
        { role: 'fast-interceptor', count: 2 },
        { role: 'heavy-gunship', count: 2 },
        { role: 'missile-platform', count: 1 },
        { role: 'shielded-warden', count: 1 },
      ],
    },
    environment: IRON_VEIL_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO EMBER CROWN' },
    ],
    scoring: {
      parTimeMs: 360000,
      baseScore: 2100,
      targetBonus: 900,
      enemyBonus: 375,
      healthBonus: 10,
      timeBonus: 1000,
      rankThresholds: { S: 10000, A: 8000, B: 6000, C: 0 },
    },
    reward: {
      id: 'finale-clearance',
      label: 'Finale Clearance',
      description: 'Command clears Skybreaker approach lanes for the final assault arc.',
    },
    unlockAfterMissionId: 'warden-break',
  },
  {
    id: 'skybreaker-gate',
    order: 7,
    title: 'SKYBREAKER GATE',
    campaignArc: 'Arc 3 // Skybreaker Finale',
    difficulty: 7,
    targetLabel: 'Gate Anchors',
    initialObjective: 'DESTROY GATE ANCHORS',
    targetDestroyedMessage: 'GATE ANCHOR DESTROYED',
    nextTargetMessage: 'GATE FIELD SHIFTING...',
    allTargetsDestroyedMessage: 'SKYBREAKER GATE OPEN // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '7 Anchors' },
      { label: 'Extraction', value: 'Gate Mouth' },
      { label: 'Threat', value: 'Command Frigate' },
    ],
    targets: [
      { id: 'anchor_0', position: [780, 0, -980], health: 135 },
      { id: 'anchor_1', position: [-120, 0, -1180], health: 135 },
      { id: 'anchor_2', position: [-980, 0, -680], health: 135 },
      { id: 'anchor_3', position: [-1080, 0, 260], health: 135 },
      { id: 'anchor_4', position: [-320, 0, 1040], health: 135 },
      { id: 'anchor_5', position: [720, 0, 920], health: 135 },
      { id: 'anchor_6', position: [1120, 0, -40], health: 135 },
    ],
    extraction: {
      label: 'Gate Mouth',
      position: [0, 0, -1380],
      activationObjective: 'RETREAT TO GATE MOUTH',
      approachObjective: 'RETREAT TO GATE MOUTH',
      completionObjective: 'MISSION COMPLETE',
      radius: 110,
    },
    enemyWave: {
      triggerTargetsDestroyed: 3,
      count: 6,
      message: 'WARNING: COMMAND FRIGATE ESCORT ARRIVING',
      composition: [
        { role: 'mini-boss', count: 1 },
        { role: 'shielded-warden', count: 1 },
        { role: 'missile-platform', count: 2 },
        { role: 'fast-interceptor', count: 2 },
      ],
    },
    environment: SIGNAL_BREAK_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO SKYBREAKER GATE' },
    ],
    scoring: {
      parTimeMs: 390000,
      baseScore: 2400,
      targetBonus: 925,
      enemyBonus: 425,
      healthBonus: 10,
      timeBonus: 1150,
      rankThresholds: { S: 11200, A: 9000, B: 6800, C: 0 },
    },
    reward: {
      id: 'gate-breach-key',
      label: 'Gate Breach Key',
      description: 'The final Skybreaker core route is exposed.',
    },
    unlockAfterMissionId: 'ember-crown',
  },
  {
    id: 'final-dawn',
    order: 8,
    title: 'FINAL DAWN',
    campaignArc: 'Arc 3 // Skybreaker Finale',
    difficulty: 8,
    targetLabel: 'Core Spires',
    initialObjective: 'DESTROY CORE SPIRES',
    targetDestroyedMessage: 'CORE SPIRE DESTROYED',
    nextTargetMessage: 'SKYBREAKER CORE ADAPTING...',
    allTargetsDestroyedMessage: 'SKYBREAKER CORE SILENCED // PROCEED TO EXTRACTION',
    briefing: [
      { label: 'Targets', value: '8 Core Spires' },
      { label: 'Extraction', value: 'Dawn Corridor' },
      { label: 'Threat', value: 'Full Response' },
    ],
    targets: [
      { id: 'core_0', position: [900, 0, -1060], health: 145 },
      { id: 'core_1', position: [0, 0, -1280], health: 145 },
      { id: 'core_2', position: [-920, 0, -980], health: 145 },
      { id: 'core_3', position: [-1240, 0, -80], health: 145 },
      { id: 'core_4', position: [-840, 0, 880], health: 145 },
      { id: 'core_5', position: [120, 0, 1220], health: 145 },
      { id: 'core_6', position: [960, 0, 820], health: 145 },
      { id: 'core_7', position: [1260, 0, -180], health: 145 },
    ],
    extraction: {
      label: 'Dawn Corridor',
      position: [1240, 0, 1050],
      activationObjective: 'RETREAT TO DAWN CORRIDOR',
      approachObjective: 'RETREAT TO DAWN CORRIDOR',
      completionObjective: 'CAMPAIGN COMPLETE',
      radius: 120,
    },
    enemyWave: {
      triggerTargetsDestroyed: 4,
      count: 7,
      message: 'WARNING: FULL RESPONSE FORCE INBOUND',
      composition: [
        { role: 'mini-boss', count: 1 },
        { role: 'shielded-warden', count: 2 },
        { role: 'missile-platform', count: 2 },
        { role: 'heavy-gunship', count: 1 },
        { role: 'fast-interceptor', count: 1 },
      ],
    },
    environment: IRON_VEIL_ENVIRONMENT,
    failureConditions: [
      { id: 'hull-depleted', label: 'Hull Integrity', message: 'CRITICAL HULL FAILURE' },
      { id: 'out-of-bounds', label: 'Mission Boundary', message: 'RETURN TO FINAL DAWN' },
    ],
    scoring: {
      parTimeMs: 450000,
      baseScore: 2800,
      targetBonus: 950,
      enemyBonus: 450,
      healthBonus: 10,
      timeBonus: 1300,
      rankThresholds: { S: 13000, A: 10400, B: 7800, C: 0 },
    },
    reward: {
      id: 'skybreaker-complete',
      label: 'Skybreaker Complete',
      description: 'Campaign complete. Replay sorties to chase better times, scores, and ranks.',
    },
    unlockAfterMissionId: 'skybreaker-gate',
  },
];

export const DEFAULT_MISSION_ID = MISSIONS[0].id;

export function getMissionById(missionId: string) {
  return MISSIONS.find(mission => mission.id === missionId) ?? MISSIONS[0];
}
